#!/usr/bin/env bash

set -x
SOURCE_DIR="$( cd -- "$(dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SOURCE_DIR/arcfls.config"

arcdir="$(date '+%d-%m-%Y_%H:%M')"
mkdir "$arcdir"

find "${DIR_LIST[@]}" -type f -size "$SIZE_LIMIT"M -mtime "$LAST_MODIFIED" -exec cp {} $arcdir ';'
tar -czf "$arcdir.zip" "$arcdir"
